#!/usr/bin/env python3
import polib, json, sys

if len(sys.argv) != 3:
    print("Usage: po2json.py input.po output.js")
    sys.exit(1)

po = polib.pofile(sys.argv[1])
out = {entry.msgid: entry.msgstr for entry in po if entry.msgstr}

with open(sys.argv[2], 'w', encoding='utf-8') as f:
    f.write("window._translations = ")
    json.dump(out, f, ensure_ascii=False, indent=2)
    f.write(";")
